name: Schedule Tests

on:
  schedule:
    - cron: '30 18 * 5 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v6

      - name: Instalar Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Instalar Chrome Driver
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & 

      - name: Run Test
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci "-Dcucumber.filter.tags=@Login"

      - name: Gerar Relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar Relatório
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: report-tests
          path: '**/cluecumber-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://compras:wiki:ufsc:br/images/1/1b/Ok:png
          SLACK_MESSAGE: 'Sucesso na execução de testes no PR :white_check_mark:'
          SLACK_TITLE: "Sucesso"
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0:gstatic:com/images?q=tbn:ANd9GcT9C8XHg9I2Z4Evn4ly4OgjbtO0sm9Z4LJ3bQ&s
          SLACK_MESSAGE: 'Falha na execução de testes no PR :proibido:'
          SLACK_TITLE: "Falha"
          SLACK_USERNAME: FALHA